safe: true
source: .
destination: ../sekigahara.gh-pages
lsi: false
#pygments: true

#auto: true
title: 不破郡関ヶ原町版 税金はどこへ行った？

code: 213624
name: 不破郡関ヶ原町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
