safe: true
source: .
destination: ../ogaki.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県大垣市
title: 岐阜県大垣市版 税金はどこへ行った？
name: 大垣市
unit: 市
code: 212024
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
