safe: true
source: .
destination: ../motosu.gh-pages
lsi: false
#pygments: true

#auto: true
title: 本巣市版 税金はどこへ行った？

code: 212181
name: 本巣市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
