safe: true
source: .
destination: ../hashima.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県羽島市
title: 岐阜県羽島市版 税金はどこへ行った？
name: 羽島市
unit: 市
code: 212091
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
