safe: true
source: .
destination: ../ono.gh-pages
lsi: false
#pygments: true

#auto: true
title: 揖斐郡大野町版 税金はどこへ行った？

code: 214035
name: 揖斐郡大野町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
