safe: true
source: .
destination: ../higashishirakawamura.gh-pages
lsi: false
#pygments: true

#auto: true
title: 加茂郡東白川村版 税金はどこへ行った？

code: 215074
name: 加茂郡東白川村
unit: 村
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
