safe: true
source: .
destination: ../mizunami.gh-pages
lsi: false
#pygments: true

#auto: true
title: 瑞浪市版 税金はどこへ行った？

code: 212083
name: 瑞浪市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
