safe: true
source: .
destination: ../mizuho.gh-pages
lsi: false
#pygments: true

#auto: true
title: 瑞穂市版 税金はどこへ行った？

code: 212164
name: 瑞穂市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
