safe: true
source: .
destination: ../kasamatsu.gh-pages
lsi: false
#pygments: true

#auto: true
title: 羽島郡笠松町版 税金はどこへ行った？

code: 213039
name: 羽島郡笠松町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
