safe: true
source: .
destination: ../anpachi.gh-pages
lsi: false
#pygments: true

#auto: true
title: 安八郡安八町版 税金はどこへ行った？

code: 213837
name: 安八郡安八町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
