safe: true
source: .
destination: ../hichiso.gh-pages
lsi: false
#pygments: true

#auto: true
title: 加茂郡七宗町版 税金はどこへ行った？

code: 215040
name: 加茂郡七宗町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
