safe: true
source: .
destination: ../ikeda.gh-pages
lsi: false
#pygments: true

#auto: true
title: 揖斐郡池田町版 税金はどこへ行った？

code: 214043
name: 揖斐郡池田町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
