safe: true
source: .
destination: ../takayama.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県高山市
title: 岐阜県高山市版 税金はどこへ行った？
name: 高山市
unit: 市
code: 212032
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
