safe: true
source: .
destination: ../kitagata.gh-pages
lsi: false
#pygments: true

#auto: true
title: 本巣郡北方町版 税金はどこへ行った？

code: 214213
name: 本巣郡北方町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
