safe: true
source: .
destination: ../kani.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県可児市
title: 岐阜県可児市版 税金はどこへ行った？
name: 可児市
unit: 市
code: 212148
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
