safe: true
source: .
destination: ../hida.gh-pages
lsi: false
#pygments: true

#auto: true
title: 飛騨市版 税金はどこへ行った？

code: 212172
name: 飛騨市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
