safe: true
source: .
destination: ../yamagata.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県山県市
title: 岐阜県山県市版 税金はどこへ行った？
name: 山県市
unit: 市
code: 212156
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
