safe: true
source: .
destination: ../kakamigahara.gh-pages
lsi: false
#pygments: true

#auto: true
title: 各務原市版 税金はどこへ行った？

code: 212130
name: 各務原市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
