safe: true
source: .
destination: ../godo.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県安八郡神戸町
title: 岐阜県安八郡神戸町版 税金はどこへ行った？
name: 神戸町
unit: 町
code: 213811
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
