safe: true
source: .
destination: ../seki.gh-pages
lsi: false
#pygments: true

#auto: true
title: 関市版 税金はどこへ行った？

code: 212059
name: 関市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
