safe: true
source: .
destination: ../gujo.gh-pages
lsi: false
#pygments: true

#auto: true
title: 郡上市版 税金はどこへ行った？

code: 212199
name: 郡上市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
