safe: true
source: .
destination: ../shirakawamura.gh-pages
lsi: false
#pygments: true

#auto: true
title: 大野郡白川村版 税金はどこへ行った？

code: 216046
name: 大野郡白川村
unit: 村
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
