safe: true
source: .
destination: ../shirakawamura.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県大野郡白川村
title: 岐阜県大野郡白川村版 税金はどこへ行った？
name: 白川村
unit: 村
code: 216046
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
