safe: true
source: .
destination: ../shirakawa.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県加茂郡白川町
title: 岐阜県加茂郡白川町版 税金はどこへ行った？
name: 白川町
unit: 町
code: 215066
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
