safe: true
source: .
destination: ../mino.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県美濃市
title: 岐阜県美濃市版 税金はどこへ行った？
name: 美濃市
unit: 市
code: 212075
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
