safe: true
source: .
destination: ../wanouchi.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県安八郡輪之内町
title: 岐阜県安八郡輪之内町版 税金はどこへ行った？
name: 輪之内町
unit: 町
code: 213829
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
