safe: true
source: .
destination: ../sekigahara.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県不破郡関ヶ原町
title: 岐阜県不破郡関ヶ原町版 税金はどこへ行った？
name: 関ヶ原町
unit: 町
code: 213624
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
