safe: true
source: .
destination: ../minokamo.gh-pages
lsi: false
#pygments: true

#auto: true
title: 美濃加茂市版 税金はどこへ行った？

code: 212113
name: 美濃加茂市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
