safe: true
source: .
destination: ../kaizu.gh-pages
lsi: false
#pygments: true

#auto: true
title: 海津市版 税金はどこへ行った？

code: 212211
name: 海津市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
