safe: true
source: .
destination: ../yoro.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県養老郡養老町
title: 岐阜県養老郡養老町版 税金はどこへ行った？
name: 養老町
unit: 町
code: 213411
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
