safe: true
source: .
destination: ../hichiso.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県加茂郡七宗町
title: 岐阜県加茂郡七宗町版 税金はどこへ行った？
name: 七宗町
unit: 町
code: 215040
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
