safe: true
source: .
destination: ../wanouchi.gh-pages
lsi: false
#pygments: true

#auto: true
title: 安八郡輪之内町版 税金はどこへ行った？

code: 213829
name: 安八郡輪之内町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
