safe: true
source: .
destination: ../nakatsugawa.gh-pages
lsi: false
#pygments: true

#auto: true
title: 中津川市版 税金はどこへ行った？

code: 212067
name: 中津川市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
