safe: true
source: .
destination: ../yamagata.gh-pages
lsi: false
#pygments: true

#auto: true
title: 山県市版 税金はどこへ行った？

code: 212156
name: 山県市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
