safe: true
source: .
destination: ../gero.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県下呂市
title: 岐阜県下呂市版 税金はどこへ行った？
name: 下呂市
unit: 市
code: 212202
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
