safe: true
source: .
destination: ../yoro.gh-pages
lsi: false
#pygments: true

#auto: true
title: 養老郡養老町版 税金はどこへ行った？

code: 213411
name: 養老郡養老町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
