safe: true
source: .
destination: ../sakahogi.gh-pages
lsi: false
#pygments: true

#auto: true
title: 加茂郡坂祝町版 税金はどこへ行った？

code: 215015
name: 加茂郡坂祝町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
