safe: true
source: .
destination: ../mitake.gh-pages
lsi: false
#pygments: true

#auto: true
title: 可児郡御嵩町版 税金はどこへ行った？

code: 215210
name: 可児郡御嵩町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
