safe: true
source: .
destination: ../kawabe.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県加茂郡川辺町
title: 岐阜県加茂郡川辺町版 税金はどこへ行った？
name: 川辺町
unit: 町
code: 215031
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
