safe: true
source: .
destination: ../ena.gh-pages
lsi: false
#pygments: true

#auto: true
title: 恵那市版 税金はどこへ行った？

code: 212105
name: 恵那市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
