safe: true
source: .
destination: ../ibigawa.gh-pages
lsi: false
#pygments: true

#auto: true
title: 揖斐郡揖斐川町版 税金はどこへ行った？

code: 214019
name: 揖斐郡揖斐川町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
