safe: true
source: .
destination: ../mino.gh-pages
lsi: false
#pygments: true

#auto: true
title: 美濃市版 税金はどこへ行った？

code: 212075
name: 美濃市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
