safe: true
source: .
destination: ../kani.gh-pages
lsi: false
#pygments: true

#auto: true
title: 可児市版 税金はどこへ行った？

code: 212148
name: 可児市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
