safe: true
source: .
destination: ../ibigawa.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県揖斐郡揖斐川町
title: 岐阜県揖斐郡揖斐川町版 税金はどこへ行った？
name: 揖斐川町
unit: 町
code: 214019
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
