safe: true
source: .
destination: ../godo.gh-pages
lsi: false
#pygments: true

#auto: true
title: 安八郡神戸町版 税金はどこへ行った？

code: 213811
name: 安八郡神戸町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
