safe: true
source: .
destination: ../kakamigahara.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県各務原市
title: 岐阜県各務原市版 税金はどこへ行った？
name: 各務原市
unit: 市
code: 212130
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
