safe: true
source: .
destination: ../tajimi.gh-pages
lsi: false
#pygments: true

#auto: true
title: 多治見市版 税金はどこへ行った？

code: 212041
name: 多治見市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
