safe: true
source: .
destination: ../hashima.gh-pages
lsi: false
#pygments: true

#auto: true
title: 羽島市版 税金はどこへ行った？

code: 212091
name: 羽島市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
