safe: true
source: .
destination: ../ikeda.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県揖斐郡池田町
title: 岐阜県揖斐郡池田町版 税金はどこへ行った？
name: 池田町
unit: 町
code: 214043
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
