safe: true
source: .
destination: ../hida.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県飛騨市
title: 岐阜県飛騨市版 税金はどこへ行った？
name: 飛騨市
unit: 市
code: 212172
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
