safe: true
source: .
destination: ../sakahogi.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県加茂郡坂祝町
title: 岐阜県加茂郡坂祝町版 税金はどこへ行った？
name: 坂祝町
unit: 町
code: 215015
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
