safe: true
source: .
destination: ../takayama.gh-pages
lsi: false
#pygments: true

#auto: true
title: 高山市版 税金はどこへ行った？

code: 212032
name: 高山市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
