safe: true
source: .
destination: ../tomika.gh-pages
lsi: false
#pygments: true

#auto: true
title: 加茂郡富加町版 税金はどこへ行った？

code: 215023
name: 加茂郡富加町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
