safe: true
source: .
destination: ../yaotsu.gh-pages
lsi: false
#pygments: true

#auto: true
title: 加茂郡八百津町版 税金はどこへ行った？

code: 215058
name: 加茂郡八百津町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
