safe: true
source: .
destination: ../ogaki.gh-pages
lsi: false
#pygments: true

#auto: true
title: 大垣市版 税金はどこへ行った？

code: 212024
name: 大垣市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
