safe: true
source: .
destination: ../kawabe.gh-pages
lsi: false
#pygments: true

#auto: true
title: 加茂郡川辺町版 税金はどこへ行った？

code: 215031
name: 加茂郡川辺町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
