safe: true
source: .
destination: ../shirakawa.gh-pages
lsi: false
#pygments: true

#auto: true
title: 加茂郡白川町版 税金はどこへ行った？

code: 215066
name: 加茂郡白川町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
