safe: true
source: .
destination: ../gero.gh-pages
lsi: false
#pygments: true

#auto: true
title: 下呂市版 税金はどこへ行った？

code: 212202
name: 下呂市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
