safe: true
source: .
destination: ../kaizu.gh-pages
lsi: false
#pygments: true

#auto: true
lname: 岐阜県海津市
title: 岐阜県海津市版 税金はどこへ行った？
name: 海津市
unit: 市
code: 212211
year: 2012
jyear: 24

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
