safe: true
source: .
destination: ../toki.gh-pages
lsi: false
#pygments: true

#auto: true
title: 土岐市版 税金はどこへ行った？

code: 212121
name: 土岐市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
