safe: true
source: .
destination: ../tarui.gh-pages
lsi: false
#pygments: true

#auto: true
title: 不破郡垂井町版 税金はどこへ行った？

code: 213616
name: 不破郡垂井町
unit: 町
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
