safe: true
source: .
destination: ../gifu.gh-pages
lsi: false
#pygments: true

#auto: true
title: 岐阜市版 税金はどこへ行った？

code: 212016
name: 岐阜市
unit: 市
year: 2011

exclude: ['Gemfile*', 'README*', 'Rakefile', 'vendor']
